### ISSUE TITLE
Tags not works for vendors 

### ISSUE THREAD

**Issue by ssathamenterprises** [weDevsOfficial/dokan#932]
Hello in my dokan pro after updates the tags not works for vendors ( I enable vendors to add tags but they can’t create tags )

**Comment by alamgircsebd** [comment]
> 
> 
> Hello in my dokan pro after updates the tags not works for vendors ( I enable vendors to add tags but they can’t create tags )

Hello @ssathamenterprises 

We have fixed this issue already, dokan next release have this updates. Now you can implement the changes follow the below instructions:

1. Open this file dokan.js from this location wp-content/plugins/dokan-lite/assets/js/dokan.js
2. Try to search line #1503
3. Add a new line `tag: true,`   [ see screenshot - http://prntscr.com/uybupp ]

Hope it will be work, let me know if you get any more problem with this. 

Thanks!

**Comment by ssathamenterprises** [comment]
Ok I try and let I know sir

**Comment by ssathamenterprises** [comment]
still not works i added the line

**Comment by ssathamenterprises** [comment]
check above image when i type the tags still shows no result found

**Comment by ssathamenterprises** [comment]
![Screenshot (39)](https://user-images.githubusercontent.com/68118999/95870302-eef59d80-0d9e-11eb-8816-cb8bd782e992.png)

**Comment by alamgircsebd** [comment]
Now we see code updated, it should be work now, if still not work please submit a ticket to support team with your site details. We will take care on it. 

Thanks!

**Comment by ssathamenterprises** [comment]
i try this line now  add ( s )    tags: true,
